### ISSUE TITLE
Not filling the view

### ISSUE THREAD

**Issue by ErAshu** [OlivierLapraye/CircleFill#1]
Hi Olivier,
I don't know why it's not working. I have simply drag a uiview and set constraints and filling this but it is not working. I am attaching example project. See the Example1 or Example 2 file. 

`thirdView.fillBackgroundFrom(point: thirdView.center, with: UIColor.red)` not working in example 2 and as well in example1

[CircleFill-master 2.zip](https://github.com/OlivierLapraye/CircleFill/files/1585043/CircleFill-master.2.zip)

**Comment by ErAshu** [comment]
@OlivierLapraye  Can you fix this?

**Comment by OlivierLapraye** [comment]
Hi ErAshu, 

I'm glad that your are interested in my work. I tried your example and cannot make it work. I will continue to investigate but i dont have a quick fix. If you have any idea of why this could happen, let met know !

Olivier

**Comment by OlivierLapraye** [comment]
I found the problem. The layer wasn't always correctly positioned in the hierarchy.
Tell me if this works for you now !
